### PR TITLE
Stay in touch (milestone 6)

### PR DESCRIPTION
**Pull request by che30**
In this mile stone we 
- Refactored the user model 
- Add logic for mutual friendship

### CODE REVIEW

**Review by Temmarie — CHANGES_REQUESTED** [review]
## Changes Required! :recycle:

### Hi @che30 and @Fanger53   ! :wave: :wave:

#### You have done well so far :clap: However, there are changes required for you to make in order for this project to be approved. Kindly work on them and submit them for another code review.


**Recommended**

- [x] Fix  your rubocop errors. Most of them can be fixed by running `rubocop -a` in your terminal.
 
#### Test

- [x] I see you've created unit test cases with Rspec but let's also create integration test cases with Rspec and Capybara at least for the Friendship features (Send, Accept, and Reject a Friend Request and see user and friends post in the Timeline)

#### That's it, team! :raised_hands: 




__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Comment by che30** [comment]
Fix rubocop errors as required and test to verify if user can accept ,reject friendship are all there too 
it 'testing user friendship and inverse frienship' do
      u1.friendships.create(friend_id: u2.id)
      expect(u1.friendships).not_to eql(u2.friendships)
    end
    it 'expects confirm_friend to make users friends' do
      u1.friendships.create(friend_id: u2.id)
      friend = User.find_by(id: u1.id)
      friendship = friend.friendships.find_by(friend_id: u2.id)
      friendship.confirm_friend
      expect(u1.friends.include?(u2)).to eql(true)
    end
    it 'expects destroy method to reject friendship' do
      u1.friendships.create(friend_id: u2.id)
      friend = User.find_by(id: u1.id)
      friendship = friend.friendships.find_by(friend_id: u2.id)
      friendship.destroy
      expect(u1.friendships.include?(u2)).to eql(false)
    end
  end
They were already in the code before the review

**Review by enaburekhan — CHANGES_REQUESTED** [review]
# Status: Request review:full_moon:
**Hi team!**
**Great job  :clap:  :clap: on making some of the changes requested by the previous Tse. However, there are still some changes to be made in order to get this project approved :muscle:.**

- [x] As highlighted by the previous Tse, kindly fix rubocop.  It seems the .rubocop.yml config has been altered in this project. see screen-shot for reference:

image

- Take some time to go through the Ror linter-config readme using this link: 

   https://github.com/microverseinc/linters-config/tree/master/ror.

- [x] Kindly correct the spelling error for Rspec on how to run the RSpec test in the readme file.

Make the above changes and request for another review.

You can reach me on slack @ Eric Enaburekhan if you have any questions.
Happy coding :blush:

**Comment by che30** [comment]
Fixed all issues as requested

**Review by enaburekhan — CHANGES_REQUESTED** [review]
# Status: Request changes  :full_moon:
Hello team!
Good job on making some of the changes as previously requested :clap:. However, You still need to make some changes to get this project approved.

- [ ] As I previously highlighted, your .rubocop,yml config has been altered and it's still yet to be fixed. see the new screen-shot for reference: 

image.
Kindly run  `check-linters-config ror` on the root of your project directory to confirm this and fix all rubocop errors.

Please make the above changes and submit another code review request.
You can reach me on slack @ Eric Enaburekhan if you need more clarifications.

Happy coding :blush:

**Review by MarilenaRoque — CHANGES_REQUESTED** [review]
# Hey guys! :rocket:

You have done a good job so far! But we still have a problem with your Github Actions configurations and your code is presenting rubocop errors.

### - [ ] Please investigate the reason why your  Rubocop-Github Actions is not running on your pull request.
Note that a ✔️  or  ❌ should appear in your commits to indicate the results of your test. 
### - [ ] Config and run it locally to make sure that your code is not presenting any rubocop errors.

Let's fix it and submit the project for a new review!

## Happy Coding! 💻 

**_Marilena Roque
Full-Stack Developer
Code Reviewer at Microverse Inc.
[Portfolio](https://mariroqueproject.com/) | [Linkedin](https://www.linkedin.com/in/roquemarilena/) 
marilenas@id.uf.br_**

**Comment by che30** [comment]
This code has no rubocop errors and it's a forked repository . When a pull request is opened with master as the base branch the github actions pass but when the branch is changed it does not

**Comment by MarilenaRoque** [comment]
## Hint:
Please, check those links about how to manually run the workflow: it will probably help you to fix that:
[Here](https://twitter.com/github/status/1321859709075394563?s=21) and [Here](https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow)

**Review by voscarmv — APPROVED** [review]
# Project status: Approved ✨ 😎👍 💯 ✔️
### You may merge this branch and move forward ⛙🛣

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

**Pull request merged**
